site_name: WARIO Documentation
repo_url: https://github.com/McMasterRS/WARIO/

nav:
    - Home: index.md
    - User Guide: 
        - Using WARIO: user/userGuide.md
        - Importing Toolkits : user/toolkits.md
        - Global Variables : user/globals.md
        - Running The Pipeline : user/pipeline.md
        
    - Developer Guide: 
        - Custom Nodes : developer/nodes.md
        - Custom Settings: developer/settings.md
        - Custom Global Inputs: developer/globals.md
        - Building Toolkits: developer/toolkits.md
        
    
theme: readthedocs